language: cpp
node_js:
 - "6"

services:
  - redis-server
addons:
  apt:
    sources:
      - kubuntu-backports
    packages:
      - xvfb
      - cmake
      - imagemagick
      - dos2unix
      - libosmesa6-dev
      - libegl1-mesa-dev
      
install:
  - npm install -g mocha

script:
  - mkdir -p ~/local
  - git clone https://github.com/glfw/glfw.git
  - cd glfw
  - mkdir build
  - cd build
  - cmake -DBUILD_SHARED_LIBS=ON ..
  - cmake --build .
  - ls -lR
  - cd ../..
  - git clone https://github.com/nigels-com/glew.git
  - cd glew
  - GLEW_DEST=~/local make
  - make install
  - cd ..
  - git clone https://github.com/mruby/mruby.git
  - cd mruby
  - cp -f ../build_config.rb .
  - CLFAGS=-I~/local/include rake
