language: cpp
node_js:
 - "6"

services:
  - redis-server
addons:
  apt:
    sources:
      - kubuntu-backports
    packages:
      - xvfb
      - cmake
      - imagemagick
      - dos2unix
      - libosmesa6-dev
      - libegl1-mesa-dev
      - libass-dev
      - libfreetype6-dev
      - libtheora-dev
      - libtool
      - libvorbis-dev
      - pkg-config 
      - texinfo 
      - zlib1g-dev
      - yasm
      - libx264-dev
      
install:
  - nvm install 6
  - nvm use 6
  - npm install -g mocha
  - npm install nightmare
  - git clone https://github.com/eddieantonio/imgcat
  - cd imgcat;CC=clang make;cd ..
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 640x480x24 > /dev/null 2>&1 &
  - mkdir -p $HOME/local/lib
  - mkdir $HOME/local/include
  - git clone https://github.com/glfw/glfw.git
  - cd glfw
  - mkdir build
  - cd build
  - cmake -DBUILD_SHARED_LIBS=ON ..
  - cmake --build .
  - cp -r ../include/GLFW $HOME/local/include
  - cp src/libglfw.so* $HOME/local/lib
  - cd ../..
  - git clone https://github.com/nigels-com/glew.git
  - cd glew
  - git checkout glew-2.0.0
  - export GLEW_DEST=$HOME/local
  - make extensions
  - make
  - make install
  - cd ..
  - gem install fluentd -v "~> 0.12.0" --no-ri --no-rdoc
  - fluentd -c ./test/fluent.conf -vv &
  - wget http://ffmpeg.org/releases/ffmpeg-snapshot.tar.bz2
  - tar xjvf ffmpeg-snapshot.tar.bz2
  - cd ffmpeg
  - ./configure --prefix=$HOME/local --enable-gpl --enable-libx264 && make > /dev/null 2>&1 && make install
  - cd ..
  
script:
  - export PATH=$PATH:$HOME/local/bin
  - export CFLAGS=-I$HOME/local/include
  - export LDFLAGS="-L$HOME/local/lib -L$HOME/local/lib64"
  - rake
  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$HOME/local/lib:$HOME/local/lib64
  - mruby/bin/mruby test/test.rb > test.ppm
  - convert test.ppm test.jpg
  - imgcat/src/imgcat --width 90 test.jpg
#  - for num in `seq 10 90`; do cp test.ppm static/test$num.ppm ;done
#  - ls -l static
#  - sh test/testFfmpeg.sh
  - mruby/bin/mruby web.rb &
  - mruby/bin/mruby main.rb &
  - mocha --reporter spec --timeout 15000
  - ls -l static
  - killall -TERM ruby
