language: cpp
node_js:
 - "6"

services:
  - redis-server
addons:
  apt:
    packages:
      - xvfb
      - imagemagick

install:
  - npm install -g mocha

script:
  - git clone https://github.com/mruby/mruby.git
  - cd mruby
  - cp -f ../build_config.rb .
  - rake
