language: cpp
node_js:
 - "6"

services:
  - redis-server
addons:
  apt:
    sources:
      - kubuntu-backports
    packages:
      - xvfb
      - cmake
      - imagemagick
      - dos2unix
      - libosmesa6-dev
      - libegl1-mesa-dev
      
install:
  - npm install -g mocha
  - git clone https://github.com/eddieantonio/imgcat
  - cd imgcat;CC=clang make;cd ..
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 640x480x24 > /dev/null 2>&1 &

script:
  - mkdir -p $HOME/local/lib
  - mkdir $HOME/local/include
  - git clone https://github.com/glfw/glfw.git
  - cd glfw
  - mkdir build
  - cd build
  - cmake -DBUILD_SHARED_LIBS=ON ..
  - cmake --build .
  - cp -r ../include/GLFW $HOME/local/include
  - cp src/libglfw.so* $HOME/local/lib
  - cd ../..
  - git clone https://github.com/nigels-com/glew.git
  - cd glew
  - git checkout glew-2.0.0
  - export GLEW_DEST=$HOME/local
  - make extensions
  - make
  - make install
  - cd ..
  - git clone https://github.com/mruby/mruby.git
  - cd mruby
  - cp -f ../build_config.rb .
  - export CFLAGS=-I$HOME/local/include
  - export LDFLAGS="-L$HOME/local/lib -L$HOME/local/lib64"
  - rake
  - cd ..
  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$HOME/local/lib:$HOME/local/lib64
  - mruby/bin/mruby test/test.rb > test.png
  - imgcat/src/imgcat --width 90 test.png
